name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 19 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: curl https://api.day.app/B2jmef5ooBh6xyBjKmgAve/test 
